### ISSUE TITLE
SurfaceView Study

### ISSUE THREAD

**Issue by renovatio0424** [J2RK/MagicCanvas#2]
어떤 구조로 구현할지에 대한 논의를 위해 
SurfaceView, GLSurfaceView 에 대해 공부하기로 했습니다 
공부한 내용을 정리한 문서가 있으면 공유해주세요~

@jason-baek @mswukris @kha9920

**Comment by jaemin-baek** [comment]
지난 스터디에서 완료하였기에 Close 합니다.
